// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6smbTxyctO1mBJdo_vNnKuGGD4bftWOE',
    appId: '1:231265814669:web:596a77f617635cd716fac4',
    messagingSenderId: '231265814669',
    projectId: 'timer-app-9686d',
    authDomain: 'timer-app-9686d.firebaseapp.com',
    storageBucket: 'timer-app-9686d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7fPiJiqnNUpzOVHWY1mGQYNs_ejGnHww',
    appId: '1:231265814669:android:76cc9fd00ffe050216fac4',
    messagingSenderId: '231265814669',
    projectId: 'timer-app-9686d',
    storageBucket: 'timer-app-9686d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs-oeCPVl9Nu3k0-Z5poqNOEaX9_4LygM',
    appId: '1:231265814669:ios:ceec56d14383d0e516fac4',
    messagingSenderId: '231265814669',
    projectId: 'timer-app-9686d',
    storageBucket: 'timer-app-9686d.firebasestorage.app',
    iosBundleId: 'com.example.timerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs-oeCPVl9Nu3k0-Z5poqNOEaX9_4LygM',
    appId: '1:231265814669:ios:ceec56d14383d0e516fac4',
    messagingSenderId: '231265814669',
    projectId: 'timer-app-9686d',
    storageBucket: 'timer-app-9686d.firebasestorage.app',
    iosBundleId: 'com.example.timerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6smbTxyctO1mBJdo_vNnKuGGD4bftWOE',
    appId: '1:231265814669:web:e8ac3f140d05b13016fac4',
    messagingSenderId: '231265814669',
    projectId: 'timer-app-9686d',
    authDomain: 'timer-app-9686d.firebaseapp.com',
    storageBucket: 'timer-app-9686d.firebasestorage.app',
  );

}